apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels: # these are replicaset labels
    app: frontend
    tier: web
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}

  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      app: frontend
      tier: web
      project: expense
  # this is pod definition
  template:
    metadata:
      # these labels belongs to pod
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: rajesh2219/frontend:{{ .Values.deployment.imageVersion }}

        resources:
         requests:
          cpu: 100m
          memory: 128Mi
         limits:
          cpu: 100m
          memory: 128Mi

        
---
kind: Service 
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: frontend
 namespace: expense
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: frontend
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: {{ .Values.hpa.cpuutilization }}





